# https://github.com/scala-steward-org/scala-steward/pull/2714
pullRequests.grouping = [
  {
    name = "scalatest"
    filter = [
      {"group" = "org.scalatest"}
      {"group" = "org.scalatestplus"}
    ]
  }
  {
    name = "jetty"
    filter = [
      {"group" = "org.eclipse.jetty"}
      {"group" = "org.eclipse.jetty.ee11"}
    ]
  }
]
