#!/usr/bin/env bash
echo
echo Running the web application with JRebel so we can hot-reload code changes
echo
echo In another shell run the following command:
echo "    mvn scala:cc"
echo
echo Using JRebel home directory of $JAVAREBEL_HOME
MAVEN_OPTS="-noverify -javaagent:$JAVAREBEL_HOME/javarebel.jar" 
mvn jetty:run $*

