#!/usr/bin/env bash
echo
echo Runs LiveReload to auto reload the browser window if a template changes
echo
echo You must install 1.4 or later: http://github.com/mockko/livereload
echo
echo Then enable the LiveReload extension in Safari/Chrome when viewing the site
echo
livereload src

