name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: false
      matrix:
        java: [8, 25]
        scala: ['2_12', '2_13', '3']

    steps:
    - uses: actions/checkout@v6
    - name: Set up JDK
      uses: actions/setup-java@v5.2.0
      with:
        java-version: ${{ matrix.java }}
        distribution: adopt
    - uses: sbt/setup-sbt@v1
    - name: Run tests
      run: |
        case ${{ matrix.scala }} in
          "2_12")
            sbt -v '++ 2.12.x' test unidoc
            ;;
          "2_13")
            sbt -v '++ 2.13.x' test unidoc
            ;;
          "3")
            sbt -v '++ 3.x' test unidoc
            ;;
          *)
            echo "unknown scala version"
            exit 1
        esac
        git diff --exit-code
